name: 🚀 Feature Request
description: Suggest a new feature or enhancement for the Employee Recognition App
title: "[FEATURE] "
labels: ["enhancement", "feature-request"]
assignees:
  - KCoderVA

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! Please fill out this form to help us understand your request.
        
  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: What problem would this feature solve? What's the use case?
      placeholder: Describe the problem or need this feature would address...
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to see implemented?
      placeholder: Describe your ideal solution...
    validations:
      required: true
      
  - type: dropdown
    id: component
    attributes:
      label: Component Area
      description: Which part of the application would this feature affect?
      options:
        - Power Apps (User Interface)
        - Power Automate (Workflows/Automation)
        - SharePoint (Data/Lists)
        - Documentation
        - Security/Compliance
        - Other
    validations:
      required: true
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to your workflow?
      options:
        - Low - Nice to have
        - Medium - Would improve efficiency
        - High - Critical for workflow
        - Critical - Blocking current processes
    validations:
      required: true
      
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information, mockups, or references that would help?
      placeholder: Add any additional context, screenshots, or references...
