# Enforce CHANGELOG Updates - GitHub Actions Workflow

name: "Enforce CHANGELOG Updates"

on:
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  changelog-check:
    runs-on: ubuntu-latest
    name: "Verify CHANGELOG.md Updates"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch full history for proper diff

      - name: Check for CHANGELOG.md
        run: |
          if [ ! -f "CHANGELOG.md" ]; then
            echo "❌ CHANGELOG.md not found!"
            echo "::error::CHANGELOG.md file is required for this repository"
            exit 1
          fi
          echo "✅ CHANGELOG.md exists"

      - name: Validate CHANGELOG format
        run: |
          echo "🔍 Validating CHANGELOG.md format..."

          # Check for basic required sections
          if ! grep -q "# Changelog" CHANGELOG.md; then
            echo "::error::Missing '# Changelog' header"
            exit 1
          fi

          if ! grep -q "## \[Unreleased\]" CHANGELOG.md; then
            echo "::error::Missing '## [Unreleased]' section"
            exit 1
          fi

          echo "✅ CHANGELOG.md format is valid"

      - name: Check for CHANGELOG updates (PR only)
        if: github.event_name == 'pull_request'
        run: |
          echo "🔍 Checking if CHANGELOG.md was updated in this PR..."

          # Get base branch (usually main)
          BASE_SHA="${{ github.event.pull_request.base.sha }}"
          HEAD_SHA="${{ github.event.pull_request.head.sha }}"

          echo "Comparing $BASE_SHA...$HEAD_SHA"

          # Get list of changed files
          CHANGED_FILES=$(git diff --name-only $BASE_SHA...$HEAD_SHA)
          echo "Changed files:"
          echo "$CHANGED_FILES"

          # Check if CHANGELOG.md was modified
          if echo "$CHANGED_FILES" | grep -q "CHANGELOG.md"; then
            echo "✅ CHANGELOG.md was updated in this PR"
            exit 0
          fi

          # Check if changes require CHANGELOG update
          SIGNIFICANT_CHANGES=false

          # Check for source code changes
          if echo "$CHANGED_FILES" | grep -E '\.(md|js|ts|py|ps1|json|yml|yaml)$|^(src|docs|scripts|\.github)/'; then
            # Exclude certain files that don't require CHANGELOG
            EXCLUDED_PATTERN='(README\.md|\.gitignore|package-lock\.json)$'
            if echo "$CHANGED_FILES" | grep -vE "$EXCLUDED_PATTERN" | grep -E '\.(md|js|ts|py|ps1|json|yml|yaml)$|^(src|docs|scripts|\.github)/'; then
              SIGNIFICANT_CHANGES=true
            fi
          fi

          if [ "$SIGNIFICANT_CHANGES" = "true" ]; then
            echo "❌ CHANGELOG.md must be updated!"
            echo "::error::Significant changes detected but CHANGELOG.md was not updated"
            echo "Files that require CHANGELOG documentation:"
            echo "$CHANGED_FILES" | grep -vE "$EXCLUDED_PATTERN" | grep -E '\.(md|js|ts|py|ps1|json|yml|yaml)$|^(src|docs|scripts|\.github)/' | sed 's/^/  - /'
            echo ""
            echo "Please update CHANGELOG.md under the [Unreleased] section before merging."
            exit 1
          else
            echo "ℹ️ No significant changes requiring CHANGELOG update"
          fi

      - name: Check CHANGELOG content quality
        run: |
          echo "🔍 Checking CHANGELOG.md content quality..."

          # Check for proper semantic versioning format
          if ! grep -q "The format is based on.*Keep a Changelog" CHANGELOG.md; then
            echo "::warning::Consider adding 'Keep a Changelog' format reference"
          fi

          # Check for unreleased content
          UNRELEASED_SECTION=$(sed -n '/## \[Unreleased\]/,/## \[/p' CHANGELOG.md | head -n -1)

          if echo "$UNRELEASED_SECTION" | grep -q "### \(Added\|Changed\|Deprecated\|Removed\|Fixed\|Security\)"; then
            echo "✅ [Unreleased] section contains categorized changes"
          else
            echo "::warning::[Unreleased] section appears empty or uncategorized"
          fi

          # Check for proper date format in version headers
          if grep -q "## \[.*\] - [0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}" CHANGELOG.md; then
            echo "✅ Version entries use proper date format (YYYY-MM-DD)"
          fi

      - name: Suggest CHANGELOG improvements
        if: failure()
        run: |
          echo ""
          echo "💡 CHANGELOG.md Improvement Suggestions:"
          echo "----------------------------------------"
          echo "1. Follow 'Keep a Changelog' format: https://keepachangelog.com/"
          echo "2. Use semantic versioning: https://semver.org/"
          echo "3. Categorize changes under [Unreleased] section:"
          echo "   ### Added - for new features"
          echo "   ### Changed - for changes in existing functionality"
          echo "   ### Deprecated - for soon-to-be removed features"
          echo "   ### Removed - for now removed features"
          echo "   ### Fixed - for any bug fixes"
          echo "   ### Security - in case of vulnerabilities"
          echo ""
          echo "4. Example entry:"
          echo "   ## [Unreleased]"
          echo "   ### Added"
          echo "   - New feature X that does Y"
          echo "   ### Fixed"
          echo "   - Bug fix for issue Z"

  changelog-validation:
    runs-on: ubuntu-latest
    name: "Advanced CHANGELOG Validation"
    needs: changelog-check

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PowerShell
        uses: azure/powershell@v1
        with:
          azPSVersion: "latest"
          inlineScript: |
            # This step ensures PowerShell is available for validation scripts
            Write-Host "PowerShell setup complete"

      - name: Run comprehensive CHANGELOG validation
        shell: pwsh
        run: |
          if (Test-Path "scripts/validate-changelog.ps1") {
            Write-Host "🔍 Running comprehensive CHANGELOG validation..."
            & "./scripts/validate-changelog.ps1" -Detailed -ShowStatus

            if ($LASTEXITCODE -eq 0) {
              Write-Host "✅ Comprehensive validation passed"
            } elseif ($LASTEXITCODE -eq 1) {
              Write-Host "⚠️ Validation passed with warnings"
            } else {
              Write-Host "❌ Validation failed"
              exit 1
            }
          } else {
            Write-Host "ℹ️ Advanced validation script not found, skipping"
          }

      - name: Check for breaking changes
        run: |
          echo "🔍 Checking for potential breaking changes..."

          # Look for breaking change indicators in commit messages
          if git log --oneline $(git merge-base origin/main HEAD)..HEAD | grep -i "breaking\|BREAKING"; then
            echo "⚠️ Potential breaking changes detected in commit messages"
            echo "::warning::Consider documenting breaking changes in CHANGELOG.md"
          fi

          # Check if CHANGELOG mentions breaking changes
          if grep -i "breaking\|BREAKING" CHANGELOG.md; then
            echo "✅ Breaking changes are documented in CHANGELOG.md"
          fi

  # Job to comment on PR with CHANGELOG status
  pr-comment:
    if: github.event_name == 'pull_request' && (success() || failure())
    runs-on: ubuntu-latest
    needs: [changelog-check, changelog-validation]

    steps:
      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo, number } = context.issue;

            let message = "## 📋 CHANGELOG.md Status\\n\\n";

            if (context.workflow_run && context.workflow_run.conclusion === 'success') {
              message += "✅ **CHANGELOG.md validation passed!**\\n\\n";
              message += "- CHANGELOG.md exists and is properly formatted\\n";
              message += "- Changes are appropriately documented\\n";
              message += "- Format follows Keep a Changelog standards\\n";
            } else {
              message += "❌ **CHANGELOG.md validation failed!**\\n\\n";
              message += "Please ensure:\\n";
              message += "- CHANGELOG.md exists in the repository root\\n";
              message += "- Your changes are documented under `## [Unreleased]`\\n";
              message += "- Use proper categories: Added, Changed, Deprecated, Removed, Fixed, Security\\n";
              message += "- Follow [Keep a Changelog](https://keepachangelog.com/) format\\n";
            }

            message += "\\n---\\n";
            message += "*This check ensures proper documentation of all significant changes.*";

            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: number,
              body: message
            });
